### ISSUE TITLE
Equipped EasyCharms persist across saves

### ISSUE THREAD

**Issue by TheMathGeek314** [SFGrenade/SFCore#13]
I equipped a custom charm in a classic save, then later deleted and created a save (in the same slot fwiw) in godseeker mode, but the custom charm was still equipped immediately.

**Comment by SFGrenade** [comment]
i believe that part would be an issue for the modding api?

**Comment by SFGrenade** [comment]
as SFCore just uses the save slots localsettings to un-/equip custom charms

**Comment by SFGrenade** [comment]
gonna close this as i opened that modding api issue with this linked
