### ISSUE TITLE
No options

### ISSUE THREAD

**Issue by WyatIsDead** [SFGrenade/SFCore#14]
So I was modding and I updated SFCore, and then when I went to open the game the only thing that would show up was the title, with no options or anything else. I tried disabling a bunch of things but the only thing that made it work was turning off SFCore. Don't know if this is a problem with my stuff or what, but I just thought I'd tell you. Thanks for the mod by the way!

**Comment by SFGrenade** [comment]
Can you detail which mods you had installed?
And also if it was on windows/macos/linux and on that on steam/gog/xboxgamepass?

**Comment by SFGrenade** [comment]
Furthermore, if it does happen again, you can upload the `ModLog.txt` / `Player.log` files here (these are found inside the save file folder, though might contain windows username, if that is a problem)

**Comment by WyatIsDead** [comment]
Thanks for getting back to me! Sorry I took a bit to respond, I was looking
at everything and being very confused. I'm on windows and steam and I'm
using scarab. I'm currently using a long list of mods but I turned most of
them off but it still didn't work. After I submitted the issue on Github I
tried using Lumafly instead and it still didn't work. When I just tried
booting it up with scarab again nothing would work at all, apparently
trying to use both at once broke something. So I deleted and reinstalled
Hollow Knight and now it's working with SFCore. So like I said, very
confused.

**Comment by WyatIsDead** [comment]
The main mod it seems to have the biggest problem with is Charm Crab.

**Comment by SFGrenade** [comment]
alright, i'll check what exactly seems to be the problem! thanks!

**Comment by SFGrenade** [comment]
So i personally didn't have any problems starting the game with charm crab installed :/

**Comment by WyatIsDead** [comment]
So it seems like something that shouldn't have been enabled was conflicting with it, cause after I deleted everything it started working again. Thanks for all your help with this even if it was just a software thing on my side.
