### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by SFGrenade** [SFGrenade/SFCore#3]
https://github.com/SFGrenade/SFCore/blob/d9fe9df8fa073a89b214f332b37331c18f5d10e6/CharmHelper.cs#L33

can't do this, reference: [RandyKnapp/ValheimMods/issues/137#issuecomment-821889309](https://github.com/RandyKnapp/ValheimMods/issues/137#issuecomment-821889309)

**Comment by HliasOuzounis** [comment]
Hey, the game crashes on Linux when I enable this mod on Scarab. I can't pinpoint the issue but I'm willing to help. You said you can't do this, meaning it's an unsolvable problem?
